Kan-79-랜딩페이지
KEA-5th-Myaong/frontend pull request #6
Opened 2024-10-11 06:29 UTC by yeonilil

## 😀 랜딩페이지 작업

# **(애니메이션 추가 작업중)**

<br/>

## 🔎 작업 내용

- 어떤 변경 사항이 있었나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

<br/>

## 🎨 이미지 첨부

<br/>

  <br/>

## ➕ 추가 코멘트

- 모바일 반응형 기준을 수정했습니다
- public/assets/landing-page에 랜딩페이지 이미지 및 아이콘들을 정리했습니다
- tailwind pluging을 추가하여 작업했습니다

<br/>

## 🤔 Issue Ticket

- [Ticket](https://gwagseoyeon.atlassian.net/browse/KAN-114)

2024-10-11 07:29 UTC, yeonilil commented on public/assets/landing-page/section4-front.svg
요 부분 현중님이 제작해두신 post 컴포넌트 사용하는 게 나을지 이미지로 대체하는 게 나을지 의견 부탁드려요~!

2024-10-11 07:30 UTC, yeonilil commented on src/app/(route)/page.tsx
> +  const cardAnimation = {
카드 애니메이션이 제가 생각한 대로가 맞긴 한데 잘 티가 안나는 것 같아서 후에 조금 수정해볼게요 !!

2024-10-11 08:12 UTC, kimgorok commented on public/assets/landing-page/section4-front.svg
이미지로 넣는게 좋을거같아용

2024-10-11 08:15 UTC, kimgorok commented on src/app/(route)/layout.tsx
> +  },
파비콘 너무 깔끔하네요!

2024-10-11 08:19 UTC, BaekJiyeon02 requested changes
전체적인 디자인이 너무 예쁘고 구현도 예쁘게 잘 된 것 같아 좋아요👏

2024-10-11 08:19 UTC, BaekJiyeon02 commented on public/assets/landing-page/section4-front.svg
저는 이미지로 대체 하는 게 나을 것 같아요! 전체적으로 이미지로 통일하고 아래 이미지에서 "프론트엔드 개발자" 라벨 컬러만 바꾸면 될 것 같네요!

2024-10-11 08:19 UTC, BaekJiyeon02 commented on public/assets/logo-sm.svg
PP로고 왼쪽 아래에 공간이 너무 많이 비는데 잘라내는 건 어떻게 생각하시나요?? 구성할때 여백을 최소화로 하고 로고만 남아 있으면 좋을 것 같아요!

2024-10-11 08:19 UTC, BaekJiyeon02 commented on src/app/(route)/page.tsx
> +  const cardAnimation = {
이미지 별로 각각 애니메이션이 추가 되는 건 어떨까요? 서연님 애니메이션 스타일이 과하지 않아서 각자 조금씩 다르게 움직여도 퀄리티가 좋아질 것 같아요! 작은 의견 보태드립니다!☺️

2024-10-11 08:19 UTC, BaekJiyeon02 commented on public/assets/landing-page/section3-img1.svg
이 돋보기가 움직이는 애니메이션을 추가해도 좋을 것 같아요! 복잡한 작업이라면 후순위로..!

2024-10-11 08:19 UTC, BaekJiyeon02 commented on public/assets/landing-page/section3-img2.svg
하나하나 분리해서 하나씩 약간의 시간차로 나타나도 좋을 것 같아요! 이것 또한 단순한 참고 의견으로 들어주세요!

2024-10-11 08:19 UTC, BaekJiyeon02 commented on public/assets/landing-page/section4-back.svg
'백엔드 개발자' 라벨 피그마 디자인과 동일하게 수정 부탁드려요!

2024-10-11 08:35 UTC, kimgorok approved these changes
깔쌈한 랜딩페이지 만들어주셔서 감사합니다! 고생하셨습니다.

2024-10-11 08:35 UTC, kimgorok commented on tailwind.config.ts
> +  plugins: [
플러그인 만들어주셔서 감사합니다. 유용하게 쓰일거같네요!

2024-10-11 08:35 UTC, kimgorok commented on src/app/(route)/page.tsx
> +'use client';
전체적으로 아주 깔끔하고 애니메이션도 아주 이쁘네요!! 디자인 마음에듭니다!(⋈•̀ᴗ•́⋈)

그런데 이 'use client'를 랜딩 페이지의 page.tsx에 추가하면 안될거같아요.
지금은 이 랜딩페이지 전체가 클라이언트 사이드에서 로드가 되는데, 그렇게 되면 사용자가 첫 페이지에 들어왔을 때 긴 로딩시간을 경험하게 되고, SEO 최적화도 안되어 검색엔진에 저희 프로젝트를 검색했을 때 구글같은데에서 빈페이지(서버에서 가져온 html이 없어서)로 간주해서 프로젝트를 안보여주게되어요.

그래서 전체적으로 사용자한테 로드시키지 않기위해서 'use client'를 무조건으로 요구하는 부분인, useRouter와 motion을 사용하는 부분을 따로 컴포넌트 파일로 만들고, 그 컴포넌트 파일에 'use client'를 추가해 주는게 좋습니다.

물론 제 페이지도 아직 page.tsx에 'use client'를 넣은 부분이 많으니, 나중에 리팩토링 진행하면서 차차 개선해나갑시다!(´◡`)

2024-10-14 02:48 UTC, yeonilil commented on src/app/(route)/page.tsx
> +'use client';
넵 감사합니다! 신경써서 작성하겠습니다 👍

2024-10-14 05:20 UTC, BaekJiyeon02 approved these changes

2024-10-14 15:53 UTC, merged